# Generated by Django 3.0.7 on 2020-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='continent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='iso_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='new_cases',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='total_cases',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='countrydata',
            name='total_deaths',
            field=models.FloatField(null=True),
        ),
    ]
