# Generated by Django 3.0.7 on 2020-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200823_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'CountryData'},
        ),
    ]
